# Generated by Django 6.0.1 on 2026-02-09 04:27

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Тақырыбы')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Анықтама')),
                ('is_published', models.BooleanField(default=True, verbose_name='Ашық емтихан')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Жасалған уақыты')),
            ],
            options={
                'verbose_name': 'Емтихан',
                'verbose_name_plural': 'Емтихандар',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_type', models.CharField(choices=[('mcq_single', 'Бір жауапты'), ('mcq_multi', 'Көп жауапты'), ('speaking_keywords', 'Айтылым'), ('practical_code', 'Жазбаша')], max_length=32, verbose_name='Сұрақ типі')),
                ('prompt', models.TextField(verbose_name='Берілгені')),
                ('points', models.PositiveSmallIntegerField(default=1, verbose_name='Ұпай')),
            ],
            options={
                'verbose_name': 'Сұрақ',
                'verbose_name_plural': 'Сұрақтар',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='accounts/users/avatars', verbose_name='Аватар')),
                ('iin', models.CharField(max_length=36, unique=True, verbose_name='ЖСН (ИИН)')),
                ('role', models.CharField(choices=[('customer', 'Тапсырушы'), ('manager', 'Менеджер')], default='customer', max_length=16, verbose_name='Типі')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Қолданушы',
                'verbose_name_plural': 'Қолданушылар',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='ExamAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Басталды'), ('submitted', 'Жіберілді'), ('graded', 'Бағаланды'), ('cancelled', 'Болдырылмады')], default='draft', max_length=16, verbose_name='Статус')),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Басталған уақыты')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Аяқталған уақыты')),
                ('total_score', models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='Жалпы балл')),
                ('max_total_score', models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='Макс жалпы балл')),
                ('meta', models.JSONField(blank=True, default=dict, verbose_name='Қосымша дерек')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='core.exam', verbose_name='Емтихан')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_attempts', to=settings.AUTH_USER_MODEL, verbose_name='Пайдаланушы')),
            ],
            options={
                'verbose_name': 'Емтихан тапсыру',
                'verbose_name_plural': 'Емтихан тапсырулар',
            },
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Жауап')),
                ('is_correct', models.BooleanField(default=False, verbose_name='Дұрыс жауап')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='core.question', verbose_name='Сұрақ')),
            ],
            options={
                'verbose_name': 'Нұсқа',
                'verbose_name_plural': 'Нұсқалар',
            },
        ),
        migrations.CreateModel(
            name='QuestionAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_json', models.JSONField(blank=True, default=dict, verbose_name='Жауап (JSON)')),
                ('score', models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='Ұпай')),
                ('max_score', models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='Макс ұпай')),
                ('is_answered', models.BooleanField(default=False, verbose_name='Жауап берілді')),
                ('is_graded', models.BooleanField(default=False, verbose_name='Бағаланды')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Құрылған уақыты')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Жаңартылған уақыты')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='core.question', verbose_name='Сұрақ')),
            ],
            options={
                'verbose_name': 'Сұрақ жауабы',
                'verbose_name_plural': 'Сұрақ жауаптары',
            },
        ),
        migrations.CreateModel(
            name='PracticalSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('python', 'Python'), ('cpp', 'C++'), ('java', 'Java'), ('js', 'JavaScript')], default='python', max_length=16, verbose_name='Тіл')),
                ('code', models.TextField(blank=True, null=True, verbose_name='Код')),
                ('passed', models.PositiveIntegerField(default=0, verbose_name='Өткен тест саны')),
                ('failed', models.PositiveIntegerField(default=0, verbose_name='Құлаған тест саны')),
                ('total', models.PositiveIntegerField(default=0, verbose_name='Барлық тест саны')),
                ('runtime_ms', models.PositiveIntegerField(default=0, verbose_name='Runtime (ms)')),
                ('memory_kb', models.PositiveIntegerField(default=0, verbose_name='Memory (kb)')),
                ('verdict', models.CharField(blank=True, max_length=64, null=True, verbose_name='Verdict')),
                ('details', models.JSONField(blank=True, default=dict, verbose_name='Толық нәтиже (JSON)')),
                ('checked_at', models.DateTimeField(blank=True, null=True, verbose_name='Тексерілген уақыты')),
                ('question_attempt', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='practical_submission', to='core.questionattempt', verbose_name='QuestionAttempt')),
            ],
            options={
                'verbose_name': 'Practical жіберілім',
                'verbose_name_plural': 'Practical жіберілімдер',
            },
        ),
        migrations.CreateModel(
            name='MCQSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selections', to='core.option', verbose_name='Option')),
                ('question_attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mcq_selections', to='core.questionattempt', verbose_name='QuestionAttempt')),
            ],
            options={
                'verbose_name': 'MCQ таңдау',
                'verbose_name_plural': 'MCQ таңдаулар',
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_type', models.CharField(choices=[('listening', 'Тыңдалым (Listening)'), ('reading', 'Оқылым (Reading)'), ('speaking', 'Айтылым (Speaking)'), ('practical', 'Жазылым (Writing/Practical)')], default='listening', max_length=32, verbose_name='Секция түрі')),
                ('max_score', models.PositiveSmallIntegerField(default=0, verbose_name='Макс. баллы')),
                ('order', models.PositiveSmallIntegerField(default=1, verbose_name='Реттілік')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='core.exam', verbose_name='Емтихан')),
            ],
            options={
                'verbose_name': 'Секция',
                'verbose_name_plural': 'Секциялар',
            },
        ),
        migrations.AddField(
            model_name='question',
            name='section',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='core.section', verbose_name='Секция'),
        ),
        migrations.CreateModel(
            name='SectionAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Басталды'), ('submitted', 'Жіберілді'), ('graded', 'Бағаланды'), ('cancelled', 'Болдырылмады')], default='draft', max_length=16, verbose_name='Статус')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Басталған уақыты')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Аяқталған уақыты')),
                ('score', models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='Секция баллы')),
                ('max_score', models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='Макс секция баллы')),
                ('time_spent_seconds', models.PositiveIntegerField(default=0, verbose_name='Жұмсаған уақыт (сек)')),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_attempts', to='core.examattempt', verbose_name='Емтихан тапсыру')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='core.section', verbose_name='Емтихан секциясы')),
            ],
            options={
                'verbose_name': 'Секция тапсыруы',
                'verbose_name_plural': 'Секция тапсырулары',
            },
        ),
        migrations.AddField(
            model_name='questionattempt',
            name='section_attempt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_attempts', to='core.sectionattempt', verbose_name='Секция тапсыруы'),
        ),
        migrations.CreateModel(
            name='SectionMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Мәтін')),
                ('audio', models.FileField(blank=True, null=True, upload_to='exams/sounds/', verbose_name='Аудиожазба')),
                ('time_limit_seconds', models.PositiveSmallIntegerField(default=0, verbose_name='Уақыты (сек)')),
                ('order', models.PositiveSmallIntegerField(default=1, verbose_name='Реттілік')),
                ('section', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='material', to='core.section', verbose_name='Секция')),
            ],
            options={
                'verbose_name': 'Секция материалы',
                'verbose_name_plural': 'Секция материалдары',
            },
        ),
        migrations.CreateModel(
            name='SpeakingAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio', models.FileField(blank=True, null=True, upload_to='exams/speaking/', verbose_name='Аудио жауап')),
                ('transcript', models.TextField(blank=True, null=True, verbose_name='Транскрипт')),
                ('matched_count', models.PositiveSmallIntegerField(default=0, verbose_name='Табылған сөз саны')),
                ('matched_keywords', models.JSONField(blank=True, default=list, verbose_name='Табылған кілт сөздер')),
                ('question_attempt', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='speaking_answer', to='core.questionattempt', verbose_name='QuestionAttempt')),
            ],
            options={
                'verbose_name': 'Speaking жауабы',
                'verbose_name_plural': 'Speaking жауаптары',
            },
        ),
        migrations.CreateModel(
            name='SpeakingRubric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keywords', models.JSONField(blank=True, default=list, verbose_name='Кілттік сөздер')),
                ('point_per_keyword', models.PositiveSmallIntegerField(default=3, verbose_name='Әр сөзге балл')),
                ('max_points', models.PositiveSmallIntegerField(default=25, verbose_name='Максимум балл')),
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='speaking_rubric', to='core.question', verbose_name='Сұрақ')),
            ],
            options={
                'verbose_name': 'Айтылым рубрикасы',
                'verbose_name_plural': 'Айтылым рубрикалары',
            },
        ),
        migrations.CreateModel(
            name='WritingTestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_data', models.TextField(verbose_name='Енгізу')),
                ('expected_output', models.TextField(verbose_name='Шығу')),
                ('is_public', models.BooleanField(default=False, verbose_name='Is public')),
                ('weight', models.PositiveIntegerField(default=1)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_cases', to='core.question', verbose_name='Сұрақ')),
            ],
            options={
                'verbose_name': 'Жазбаша есеп',
                'verbose_name_plural': 'Жазбаша есептер',
            },
        ),
    ]
