# Generated by Django 6.0.1 on 2026-02-09 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='order',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Реттілік'),
        ),
    ]
