# Generated by Django 6.0.1 on 2026-02-10 08:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_question_section'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='examattempt',
            options={'verbose_name': 'Емтихан нәтижесі', 'verbose_name_plural': 'Емтихан нәтижелері'},
        ),
        migrations.AlterModelOptions(
            name='mcqselection',
            options={'verbose_name': 'Тест жауабы', 'verbose_name_plural': 'Тест жауаптары'},
        ),
        migrations.AlterModelOptions(
            name='practicalsubmission',
            options={'verbose_name': 'Жазбаша жауабы', 'verbose_name_plural': 'Жазбаша жауаптары'},
        ),
        migrations.AlterModelOptions(
            name='questionattempt',
            options={'verbose_name': 'Сұрақ нәтижесі', 'verbose_name_plural': 'Сұрақ нәтижелері'},
        ),
        migrations.AlterModelOptions(
            name='sectionattempt',
            options={'verbose_name': 'Секция нәтижесі', 'verbose_name_plural': 'Секция нәтижелері'},
        ),
        migrations.AlterModelOptions(
            name='speakinganswer',
            options={'verbose_name': 'Айтылым жауабы', 'verbose_name_plural': 'Айтылым жауаптары'},
        ),
        migrations.AlterField(
            model_name='mcqselection',
            name='option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selections', to='core.option', verbose_name='Нұсқа'),
        ),
        migrations.AlterField(
            model_name='mcqselection',
            name='question_attempt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mcq_selections', to='core.questionattempt', verbose_name='Сұрақ нәтижесі'),
        ),
        migrations.AlterField(
            model_name='practicalsubmission',
            name='question_attempt',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='practical_submission', to='core.questionattempt', verbose_name='Сұрақ нәтижесі'),
        ),
        migrations.AlterField(
            model_name='speakinganswer',
            name='question_attempt',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='speaking_answer', to='core.questionattempt', verbose_name='Сұрақ нәтижесі'),
        ),
    ]
