# Generated by Django 6.0.1 on 2026-02-10 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_examattempt_options_alter_mcqselection_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='time_limit_seconds',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Уақыты (сек)'),
        ),
    ]
