# Generated by Django 6.0.1 on 2026-02-10 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_section_time_limit_seconds'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='time_limit_seconds',
        ),
        migrations.AddField(
            model_name='section',
            name='time_limit',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Уақыты (мин)'),
        ),
    ]
