# Generated by Django 6.0.1 on 2026-02-10 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_section_time_limit_seconds_section_time_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examattempt',
            name='status',
            field=models.CharField(choices=[('no_started', 'Басталмаған'), ('in_progress', 'Тест өтіп жатыр'), ('finished', 'Аяқталды'), ('aborted', 'Тоқтатылды')], default='no_started', max_length=16, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='sectionattempt',
            name='status',
            field=models.CharField(choices=[('no_started', 'Басталмаған'), ('in_progress', 'Тест өтіп жатыр'), ('finished', 'Аяқталды'), ('aborted', 'Тоқтатылды')], default='no_started', max_length=16, verbose_name='Статус'),
        ),
    ]
