# Generated by Django 6.0.1 on 2026-02-11 07:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_examattempt_status_alter_sectionattempt_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='section_type',
            field=models.CharField(choices=[('listening', 'Тыңдалым (Listening)'), ('reading', 'Оқылым (Reading)'), ('speaking', 'Айтылым (Speaking)'), ('writing', 'Жазылым (Writing/Practical)')], default='listening', max_length=32, verbose_name='Секция түрі'),
        ),
        migrations.CreateModel(
            name='Writing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expected_output', models.TextField(verbose_name='Дұрыс шығару (output)')),
                ('ignore_whitespace', models.BooleanField(default=True, verbose_name='Whitespace елемеу')),
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='answer_key', to='core.question', verbose_name='Сұрақ')),
            ],
            options={
                'verbose_name': 'Жазбаша есеп',
                'verbose_name_plural': 'Жазбаша есептер',
            },
        ),
        migrations.CreateModel(
            name='WritingSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('python', 'Python'), ('cpp', 'C++'), ('java', 'Java'), ('js', 'JavaScript')], default='python', max_length=16, verbose_name='Тіл')),
                ('code', models.TextField(blank=True, null=True, verbose_name='Код')),
                ('output_text', models.TextField(blank=True, null=True, verbose_name='Жауап (output)')),
                ('is_correct', models.BooleanField(default=False, verbose_name='Дұрыс')),
                ('checked_at', models.DateTimeField(blank=True, null=True, verbose_name='Тексерілген уақыты')),
                ('question_attempt', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='writing_submission', to='core.questionattempt', verbose_name='Сұрақ нәтижесі')),
            ],
            options={
                'verbose_name': 'Жазбаша жауабы',
                'verbose_name_plural': 'Жазбаша жауаптары',
            },
        ),
    ]
