# Generated by Django 6.0.1 on 2026-02-11 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_section_section_type_writing_writingsubmission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='writingtestcase',
            name='question',
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('mcq_single', 'Бір жауапты'), ('mcq_multi', 'Көп жауапты'), ('speaking_keywords', 'Айтылым'), ('writing', 'Жазбаша')], max_length=32, verbose_name='Сұрақ типі'),
        ),
        migrations.DeleteModel(
            name='PracticalSubmission',
        ),
        migrations.DeleteModel(
            name='WritingTestCase',
        ),
    ]
