# Generated by Django 6.0.1 on 2026-02-11 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_writingtestcase_question_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='writing',
            name='question',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='writing', to='core.question', verbose_name='Сұрақ'),
        ),
    ]
