# Generated by Django 6.0.1 on 2026-02-11 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_writing_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sectionmaterial',
            name='order',
        ),
    ]
