# Generated by Django 6.0.1 on 2026-02-16 07:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_sectionmaterial_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='section_material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='core.sectionmaterial'),
        ),
        migrations.AlterField(
            model_name='sectionmaterial',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='core.section', verbose_name='Секция'),
        ),
    ]
