# Generated by Django 6.0.1 on 2026-02-16 07:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_question_section_material_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questionattempt',
            options={'ordering': ['order', 'id'], 'verbose_name': 'Сұрақ нәтижесі', 'verbose_name_plural': 'Сұрақ нәтижелері'},
        ),
        migrations.AddField(
            model_name='questionattempt',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='questionattempt',
            name='section_material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='question_attempts', to='core.sectionmaterial', verbose_name='Таңдалған материал'),
        ),
        migrations.AddConstraint(
            model_name='questionattempt',
            constraint=models.UniqueConstraint(fields=('section_attempt', 'question'), name='uniq_question_per_section_attempt'),
        ),
    ]
