# Generated by Django 6.0.1 on 2026-02-16 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_questionattempt_options_questionattempt_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectionmaterial',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Белсенді'),
        ),
        migrations.AddField(
            model_name='sectionmaterial',
            name='order',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Реттілік'),
        ),
    ]
