# Generated by Django 6.0.1 on 2026-02-17 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_sectionmaterial_is_active_sectionmaterial_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionattempt',
            name='option_order',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
